<?php

namespace app\modules\femida\controllers;

use admin\models\Admin;
use common\models\Franchise;
use common\models\FranchiseCases;
use common\models\FranchisePackage;
use common\models\FranchiseReviews;
use common\models\Map;
use common\models\News;
use common\models\Technologies;
use yii\helpers\Url;
use Yii;
use yii\web\Response;

class MainController extends \yii\web\Controller
{

    public function beforeAction($action)
    {
        Yii::$app->session->set('voronka', 108);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'femida.force, фемида форс, купить франшизу, продать франшизу, купить бизнес, продажа готового бизнеса, покупка готового бизнеса, новости франчайзинга']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'FEMIDA.FORCE — это бизнес-сообщество, которое позволяет открыть свое дело в различных сферах бизнеса, где мы являемся гарантами конверсии и бизнес-показателей.']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Франшиза готовый бизнес с нуля']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'FEMIDA.FORCE — это бизнес-сообщество, которое позволяет открыть свое дело в различных сферах бизнеса, где мы являемся гарантами конверсии и бизнес-показателей.']);
//        $franchaiz = Franchise::find()->orderBy('id desc')->all();
        $regions = [];
        foreach (Map::$regions as $item){
            $regions[$item] = Map::getByRegion($item);
        }
        if (!empty($_GET['filters'])){
            $franchFilter = $_GET['filters'];
            $filters = ['AND'];
            if (!empty($franchFilter['price'])){
                if($franchFilter['price'] == 'Any'){
                    $filters[] = ['>','price', 0];
                } elseif ($franchFilter['price'] == 90000){
                    $filters[] = ['<','price', 100000];
                } elseif ($franchFilter['price'] == 300000){
                    $filters[] = ['AND', ['>=', 'price', 100000], ['<', 'price', 500000]];
                } else {
                    $filters[] = ['>=', 'price', 500000];
                }
            }
            if(!empty($franchFilter['category'])){
                if($franchFilter['category'] !== 'all'){
                    $filters[] = ['category' => $franchFilter['category']];
                }
            }
            $franchaiz = Franchise::find()->select(['id', 'category', 'link', 'name', 'price', 'vendor'])->where($filters)->all();
        } else{
            $franchaiz = Franchise::find()->orderBy('id desc')->all();
        }

        $categoryFilter = Franchise::find()->select('category')->distinct()->asArray()->all();
        $news = News::find()->orderBy('id desc')->where(['OR',['tag' => 'главная'],['tag' => 'общие']])->limit(5)->all();
        return $this->render('index', ['regions' => $regions, 'news' => $news, 'categoryFilter'=>$categoryFilter ,'franchaiz' => $franchaiz]);
    }
    public function actionGetRegionsAjax() {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (isset($_POST['find'])) {
            $value = $_POST['find'];
            $regionsRends = new Admin('clients');
            return $regionsRends->getAjaxGeo($value);
        } else
            return ['status' => 'error', 'message' => "Поисковое значение не найдено"];
    }
    public function actionKakKupitFranchizy()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'купить франшизу, как купить франшизу, выгодные франшизы, как проверить франшизу,']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Расскажем о том, как выгодно получить франшизу']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Как купить франшизу: пошаговая инструкция, чтобы не потерять деньги']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Расскажем о том, как выгодно получить франшизу']);

        $news = News::find()->orderBy('id desc')->where(['OR',['tag' => 'главная'],['tag' => 'общие']])->limit(5)->all();
        return $this->render('kak-kupit-franchizy', ['news' => $news]);
    }
    public function actionKakCovidPovliyalNaRaskladSil()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'covid-19, влияние пандемии на бизнес, covid и бизнес']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Расскажем о том, как пандемия изменила привычный образ жизни в различных сферах бизнеса, а именно на страховом рынке']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Как COVID-19 повлиял на расклад сил на страховом рынке']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Расскажем о том, как пандемия изменила привычный образ жизни в различных сферах бизнеса, а именно на страховом рынке']);
        $news = News::find()->orderBy('id desc')->where(['OR',['tag' => 'главная'],['tag' => 'общие']])->limit(5)->all();
        return $this->render('kak-covid-povliyal-na-rasklad-sil', ['news' => $news]);
    }
    public function actionChtoTakoeFranchaizing()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Что такое франчайзинг, кто такой франчайзер, что такое франшиза']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Расскажем о том, что такое франчайзинг, чем она отличается от других форм бизнеса, кем являются франчайзер и франчайзи, какие они имеют права и др.']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Что такое франчайзинг: нормы и законы']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Что такое франчайзинг: нормы и законы']);
        $news = News::find()->orderBy('id desc')->where(['OR',['tag' => 'главная'],['tag' => 'общие']])->limit(5)->all();
        return $this->render('chto-takoe-franchaizing', ['news' => $news]);
    }
    public function actionKakPolychitVozvratDeneg()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Возврат денег за франшизу, как вернуть деньги за франшизу, не удалась франшиза']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Расскажем о том, какие существуют причины, этапы и другие способы расторжения договора']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Как получить возврат денег за франшизу: что делать, если она не удалась']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Расскажем о том, какие существуют причины, этапы и другие способы расторжения договора']);
        $news = News::find()->orderBy('id desc')->where(['OR',['tag' => 'главная'],['tag' => 'общие']])->limit(5)->all();
        return $this->render('kak-polychit-vozvrat-deneg', ['news' => $news]);
    }
    public function actionKakVubratHoroshyuFranchizy()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'как выбрать франшизу, виды франшиз, преимущества франших, недостатки франшиз']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Расскажем о том, какие существуют виды франшиз, а также их преимущества и недостатки']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Как выбрать хорошую франшизу при банкротстве?']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Расскажем о том, какие существуют виды франшиз, а также их преимущества и недостатки']);
        $news = News::find()->orderBy('id desc')->where(['OR',['tag' => 'главная'],['tag' => 'общие']])->limit(5)->all();
        return $this->render('kak-vubrat-horoshyu-franchizy', ['news' => $news]);
    }
    public function actionViduFranchizy()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Виды франшиз, классификается франшиз, какие бывают франшизы']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Расскажем о том, какие существуют виды франшиз, поделенные по характеру взаимоотношений']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Виды франшиз: классификация по характеру взаимоотношений']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Расскажем о том, какие существуют виды франшиз, поделенные по характеру взаимоотношений']);
        $news = News::find()->orderBy('id desc')->where(['OR',['tag' => 'главная'],['tag' => 'общие']])->limit(5)->all();
        return $this->render('vidu-franchizy', ['news' => $news]);
    }
    public function actionAbout()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'myforce, майфорс, фемида форс, femida.force, готовые решения для бизнеса']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Узнайте больше о проекте MYFORCE, а так-же о первом дочернем проекте FEMIDA.FORCE!']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'О проекте FEMIDA.FORCE']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Узнайте больше о проекте MYFORCE, а так-же о первом дочернем проекте FEMIDA.FORCE!']);
        return $this->render('about');
    }
    public function actionPartnership()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Продать франшизу, продать бизнес, найти партнеров']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Мы поможем продать фашу франшизу, решив все ваши сложности! Для нас качество на первом месте!']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Продавайте свою франшизу вместе с надежным партнером']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Мы поможем продать фашу франшизу, решив все ваши сложности! Для нас качество на первом месте!']);
        return $this->render('partnership');
    }
    public function actionFranchize($link)
    {

        $regions = [];
        foreach (Map::$regions as $item){
            $regions[$item] = Map::getByRegion($item);
        }
        if(!empty($link)){
            $franch = Franchise::findOne(['link'=>$link]);
            $this->view->registerMetaTag(['name' => 'keywords', 'content' => $franch['meta_keywords']]);
            $this->view->registerMetaTag(['name' => 'description', 'content' => $franch['meta_description']]);
            $this->view->registerMetaTag(['property' => 'og:title', 'content' => $franch['name']]);
            $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
            $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
            $this->view->registerMetaTag(['property' => 'og:description', 'content' => $franch['meta_description']]);
            if(!empty($franch)){
                $package = FranchisePackage::find()->where(['franchise_id'=>$franch->id])->orderBy('id')->all();
                $cases = FranchiseCases::find()->where(['franchise_id'=>$franch->id])->orderBy('id desc')->all();
                $reviews = FranchiseReviews::find()->where(['franchise_id'=>$franch->id])->orderBy('id desc')->all();
                $reviewses = FranchiseReviews::find()->where(['franchise_id'=>$franch->id])->limit(3)->orderBy('id desc')->all();
                $technologies = Technologies::find()->limit(4)->orderBy(['rand()' => SORT_DESC])->where(['category' => $franch->category])->asArray()->all();
                if (!empty($technologies)){
                    foreach ($technologies as $item){
                        $popupdata[$item['id']] = ($item);
                    }
                } else{
                    $popupdata = [];
                }
                $videoshow = [];
                foreach ($cases as $item){
                    $videoshow[$item['id']] = $item['video'];
                }
                return $this->render('franchize', ['franch' => $franch, 'region' => $regions, 'package' => $package, 'cases' => $cases, 'reviews' => $reviews, 'technologies' => $technologies, 'videoshow' => $videoshow, 'popupdata' => $popupdata, 'reviewses' => $reviewses]);
            } else return Yii::$app->response
                ->redirect(Url::to(['index']));
        } else return Yii::$app->response
            ->redirect(Url::to(['index']));
    }
    public function actionNews($link)
    {

        if(!empty($link)){
            $article = News::findOne(['link'=>$link]);
            $this->view->registerMetaTag(['name' => 'keywords', 'content' => $article['meta_keywords']]);
            $this->view->registerMetaTag(['name' => 'description', 'content' => $article['meta_description']]);
            $this->view->registerMetaTag(['property' => 'og:title', 'content' => $article['og_title']]);
            $this->view->registerMetaTag(['property' => 'og:type', 'content' => 'article']);
            $this->view->registerMetaTag(['property' => 'og:image', 'content' => $article['og_image']]);
            $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
            $this->view->registerMetaTag(['property' => 'og:description', 'content' => $article['meta_description']]);
            if(!empty($article)){
                $news = News::find()
                    ->where(['!=','id',$article->id])
                    ->orderBy('id desc')
                    ->limit(5)
                    ->all();
                return $this->render('news', ['news' => $news, 'article' => $article]);
            } else return Yii::$app->response
                ->redirect(Url::to(['index']));
        } else return Yii::$app->response
            ->redirect(Url::to(['index']));
    }
    public function actionFranchizes()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Франшизы фемида форс, франшизы femida.force, технологи femida.force,
технологии фемида форс, технологии для бизнеса, франшизы для бизнеса']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Вы можете подобрать подходящую для Вас франшизу, а так-же посмотреть 
технологии которые у нас применяются!']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Технологии FEMIDA.FORCE']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Вы можете подобрать подходящую для Вас франшизу, а так-же посмотреть 
технологии которые у нас применяются!']);
//        $franchaiz = Franchise::find()->orderBy('id desc')->all();
        if (!empty($_GET['filters'])){
            $franchFilter = $_GET['filters'];
            $filters = ['AND'];
            if (!empty($franchFilter['price'])){
                if($franchFilter['price'] == 'Any'){
                    $filters[] = ['>','price', 0];
                } elseif ($franchFilter['price'] == 90000){
                    $filters[] = ['<','price', 100000];
                } elseif ($franchFilter['price'] == 300000){
                    $filters[] = ['AND', ['>=', 'price', 100000], ['<', 'price', 500000]];
                } else {
                    $filters[] = ['>=', 'price', 500000];
                }
            }
            if(!empty($franchFilter['category'])){
                if($franchFilter['category'] !== 'all'){
                    $filters[] = ['category' => $franchFilter['category']];
                }
            }
            $franchaiz = Franchise::find()->select(['id', 'category', 'link', 'name', 'price', 'vendor'])->where($filters)->all();
        } else{
            $franchaiz = Franchise::find()->orderBy('id desc')->all();
        }
        $categoryFilter = Franchise::find()->select('category')->distinct()->asArray()->all();
        $technologies = Technologies::find()->orderBy('id desc')->asArray()->all();
        $videoshow = [];
        foreach ($technologies as $item){
            $popupdata[$item['id']] = ($item);
        }
        return $this->render('franchizes', ['franchaiz' => $franchaiz, 'technologies' => $technologies, 'popupdata' => $popupdata, 'categoryFilter' => $categoryFilter]);
    }


    public function actionTechnologies()
    {
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Франшизы фемида форс, франшизы femida.force, технологи femida.force,
технологии фемида форс, технологии для бизнеса, франшизы для бизнеса']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Вы можете подобрать подходящую для Вас франшизу, а так-же посмотреть 
технологии которые у нас применяются!']);
        $this->view->registerMetaTag(['property' => 'og:title', 'content' => 'Технологии FEMIDA.FORCE']);
        $this->view->registerMetaTag(['property' => 'og:image', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:url', 'content' => '']);
        $this->view->registerMetaTag(['property' => 'og:description', 'content' => 'Вы можете подобрать подходящую для Вас франшизу, а так-же посмотреть 
технологии которые у нас применяются!']);
        if (!empty($_GET['filters'])){
            $franchFilter = $_GET['filters'];
            $filters = ['AND'];
            if(!empty($franchFilter['category'])){
                if($franchFilter['category'] !== 'all'){
                    $filters[] = ['category' => $franchFilter['category']];
                }
            }
            $franchaiz = Technologies::find()->orderBy('id desc')->where($filters)->all();
        } else{
            $franchaiz = Technologies::find()->orderBy('id desc')->all();
        }
        $categoryFilter = Franchise::find()->select('category')->distinct()->asArray()->all();
        $technologies = Technologies::find()->orderBy('id desc')->asArray()->all();
        $videoshow = [];
        foreach ($technologies as $item){
            $popupdata[$item['id']] = ($item);
        }
        return $this->render('technologies', ['franchaiz' => $franchaiz, 'technologies' => $technologies, 'popupdata' => $popupdata, 'categoryFilter' => $categoryFilter]);
    }
}
