<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "dev_project".
 *
 * @property int $id ID
 * @property int $user_id ID пользователя
 * @property string $type Тип проекта
 * @property string $name Название проекта
 * @property string|null $date_end Предварительная дата завершения
 * @property string $status Статус проекта
 * @property int $stage_id Стадия проекта
 * @property string $about_project О проекте
 * @property string $link Ссылка на проект
 * @property string|null $tz_link Ссылка на ТЗ
 * @property int $summ Стоимость проекта
 * @property string $date Дата создания
 */
class DevProject extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'dev_project';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'stage_id', 'type', 'name', 'status', 'about_project', 'link', 'summ'], 'required'],
            [['user_id', 'stage_id', 'summ'], 'integer'],
            [['type', 'status', 'about_project'], 'string'],
            [['date_end', 'date'], 'safe'],
            [['name'], 'string', 'max' => 511],
            [['link'], 'string', 'max' => 255],
            [['tz_link'], 'string', 'max' => 1023],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Пользователь',
            'type' => 'Тип проекта',
            'name' => 'Название проекта',
            'date_end' => 'Предварительная дата завершения',
            'status' => 'Статус проекта',
            'stage_id' => 'Стадия проекта',
            'about_project' => 'О проекте',
            'link' => 'Ссылка на проект',
            'tz_link' => 'Ссылка на ТЗ',
            'summ' => 'Стоимость проекта',
            'date' => 'Дата создания',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!$insert){
            if (isset($changedAttributes['stage_id'])){
                $models = DevProjectAllias::find()->asArray()->where(['project_id' => $this->id])->select('stage_id')->all();
                $arr = [];
                foreach ($models as $v)
                    $arr[] = $v['stage_id'];
                if (!in_array($changedAttributes['stage_id'], $arr)){
                    $model = new DevProjectAllias();
                    $model->project_id = $this->id;
                    $model->stage_id = $changedAttributes['stage_id'];
                    $model->date = date('Y-m-d H:i:s');
                    $model->save();
                }
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
