<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "integrations".
 *
 * @property int $id ID
 * @property string $entity Сущность
 * @property int $entity_id ID сущности
 * @property int|null $user_id Пользователь
 * @property string $integration_type Тип интеграции
 * @property string|null $config Конфигурация
 * @property string $date Дата создания
 * @property string $uuid UUID
 */
class Integrations extends \yii\db\ActiveRecord
{
    public $url;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'integrations';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['entity', 'entity_id', 'integration_type'], 'required'],
            [['entity', 'integration_type', 'config', 'url'], 'string'],
            [['config'], 'default', 'value' => '{}'],
            [['entity_id', 'user_id'], 'integer'],
            [['date'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'entity' => 'Сущность',
            'entity_id' => 'ID сущности',
            'user_id' => 'Пользователь',
            'integration_type' => 'Тип интеграции',
            'config' => 'Конфигурация',
            'date' => 'Дата создания',
            'uuid' => 'UUID',
        ];
    }

    public function makeUUID () {
        return vsprintf( '%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex(random_bytes(16)), 4) );
    }

    public function beforeValidate()
    {
        if (empty($this->uuid))
            $this->uuid = $this->makeUUID();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

}
